In [22]:
import pandas as pd
a=pd.read_csv('/content/train.csv')
print(a)

      battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0               842     0          2.2         0   1       0           7   
1              1021     1          0.5         1   0       1          53   
2               563     1          0.5         1   2       1          41   
3               615     1          2.5         0   0       0          10   
4              1821     1          1.2         0  13       1          44   
...             ...   ...          ...       ...  ..     ...         ...   
1995            794     1          0.5         1   0       1           2   
1996           1965     1          2.6         1   0       0          39   
1997           1911     0          0.9         1   1       1          36   
1998           1512     0          0.9         0   4       1          46   
1999            510     1          2.0         1   5       1          45   

      m_dep  mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  \
0       

In [23]:
y=a['price_range']
print(y)

0       1
1       2
2       2
3       2
4       1
       ..
1995    0
1996    2
1997    3
1998    0
1999    3
Name: price_range, Length: 2000, dtype: int64


In [24]:
print(max(y))
print(min(y))

3
0


In [ ]:
x=a.drop(columns=['price_range'])
print(x)

In [26]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler(feature_range=(0,1))
x_train=scaler.fit_transform(x);

In [ ]:
print(x_train)

In [ ]:
from sklearn.model_selection import train_test_split
z=train_test_split(x_train)
print(z)

In [ ]:
a1=pd.read_csv('/content/heart.csv')
print(a1)
y=a1['target']
x=a1.drop(columns=['target'])

In [ ]:
print(x)
print(y)

In [60]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler(feature_range=(0,1))
x1_train=scaler.fit_transform(x);
print(x1_train)
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x1_train,y,test_size=0.3)
print(x_train.shape,y_train.shape,x_test.shape,y_test.shape)#x_train_shape=(212,13) ,y_train_shape=(212,)

[[0.70833333 1.         1.         ... 0.         0.         0.33333333]
 [0.16666667 1.         0.66666667 ... 0.         0.         0.66666667]
 [0.25       0.         0.33333333 ... 1.         0.         0.66666667]
 ...
 [0.8125     1.         0.         ... 0.5        0.5        1.        ]
 [0.58333333 1.         0.         ... 0.5        0.25       1.        ]
 [0.58333333 0.         0.33333333 ... 0.5        0.25       0.66666667]]
(212, 13) (212,) (91, 13) (91,)


In [67]:
import numpy as np
def perceptron(w, b):
    y_p = []
    for i in range(len(x_train)):
        z = np.dot(x_train[i], w) + b
        s = 1 / (1 + np.exp(-z))
        if s >= 0.5:
            y_p.append(1)
        else:
            y_p.append(0)
    return y_p

weights = np.ones(x_train.shape[1])
bias = 0
predicted = perceptron(weights, bias)
print(len(predicted))
print(np.ones(x_train.shape[1]))
#print(predicted)
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_train, predicted)
print(f"Accuracy: {accuracy:.2f}")

212
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
Accuracy: 0.57
